name: 🚧 Blocked (external dependency)
description: Task waiting on an external event
title: "[BLOCKED] "
labels: ["blocked"]
body:
  - type: textarea
    id: description
    attributes:
      label: Task description
    validations:
      required: true
  - type: textarea
    id: blocker
    attributes:
      label: What's blocking it?
      placeholder: "Third-party API unavailable, waiting on client approval, another PR to merge..."
    validations:
      required: true
  - type: input
    id: eta
    attributes:
      label: Estimated unblock date
      placeholder: "If known"
