name: Feature / Enhancement
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What need / pain point does this feature address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the desired functionality
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches you've considered
  - type: dropdown
    id: priority
    attributes:
      label: Estimated priority
      options:
        - Nice to have
        - Useful
        - Important
        - Critical
